name = "maintenance-worker"
main = "src/index.js"
compatibility_date = "2024-03-20"

[vars]
API_URL = "https://api.your-domain.com"

[[kv_namespaces]]
binding = "MAINTENANCE_PAGES"
id = "maintenance-pages"
preview_id = "maintenance-pages-preview" 